scara_v2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint1
    pid: {p: 5000.0, i: 5, d: 500.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint2
    pid: {p: 5000.0, i: 5, d: 500.0}

  #jointGripperBase_position_controller:
   # type: effort_controllers/JointPositionController
   # joint: Joint_GripperBase
   # pid: {p: 5000.0, i: 5, d: 500.0}
  #jointGripper_position_controller:
   # type: effort_controllers/JointPositionController
    #joint: Joint_Gripper
    #pid: {p: 50000, i: 5, d: 500.0}
