scara_and_rt:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


  # Position Controllers SCARA ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint1
    pid: {p: 200.0, i: 4.0, d: 2.5}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint2
    pid: {p: 200.0, i: 4.0, d: 2.5}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_GripperBase
    pid: {p: 250.0, i: 5.0, d: 10.0}


  # Position Controllers ROTARY TABLE ---------------------------------
  rt_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link1_to_link1
    pid: {p: 100.0, i: 1.0, d: 15.0}
