scara_v2_full:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint1
    pid: {p: 500.0, i: 2.0, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint2
    pid: {p: 500.0, i: 2.0, d: 10.0}

#  jointGripperBase_position_controller:
#    type: effort_controllers/JointStateController
#    joint: Joint_GripperBase
#    pid: {p: 20.0, i: 0.2, d: 0.5}

  #jointGripper_position_controller:
   # type: effort_controllers/JointPositionController
    #joint: Joint_Gripper
    #pid: {p: 50000, i: 5, d: 500.0}
