scara_and_rt:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - Joint1
      - Joint2
      - Joint_GripperBase
#      - base_link1_to_link1
    gains:
      Joint1: {p: 150.0, i: 2.0, d: 10.0, i_clamp: 0.0}
      Joint2: {p: 150.0, i: 2.0, d: 10.0, i_clamp: 0.0}
      Joint_GripperBase: {p: 200.0, i: 2.0, d: 15.0, i_clamp: 0.0}
#      base_link1_to_link1: {p: 100.0, i: 1.0, d: 15.0, i_clamp: 0.0}
    constraints:
      goal_time: 1
      Joint1:
        goal: 0.1
      Joint2:
        goal: 0.1
      Joint_GripperBase:
        goal: 0.1
#      base_link1_to_link1:
#        goal: 0.1



